### PR TITLE
Coverity scan

### PR DESCRIPTION
**Pull request by petehayes**
Integrated the coverity scan process into the travis system.  For now, you have to push to the coverity scan branch to trigger the scan.

### CODE REVIEW

**Comment by cdancy** [comment]
@petehayes you whipped that together pretty quick!

Can you spread the access/admin rights for coverity? Seems like all users should be able to click on the badge and view. It's giving me a "You're not authorized to view this page" message. Maybe a config to open that up globally?

**Comment by petehayes** [comment]
I will check.

**Comment by petehayes** [comment]
I think this is because there is a manual review on the coverity side of the project.  Did you sign up with coverity?

**Comment by cdancy** [comment]
I did or rather I logged in with my github account.

docker-java uses coverity and you're able to anonymously click the badge and be brought to the report.

https://github.com/docker-java/docker-java

**Comment by petehayes** [comment]
I am pretty sure it is due to the wait period for manual review on coverity's side.  Can you request access to the project in coverity?  I see an option for approving people to join.

**Comment by cdancy** [comment]
No I _think_ something is up. If I go to search for this project on [coverity](https://scan.coverity.com/projects?utf8=%E2%9C%93&search=lily-mistral%2Fsample-java-project) the search results come up empty. Maybe there is a waiting period for it to show up?

Also ... docker-java has their coverity badge link to the below URL which is different than the project URL on our page. Looks like some sort of unique ID is being used.

https://scan.coverity.com/projects/9177

**Pull request merged**
