### PR TITLE
Bumped gradle version, configured wrapper and add intellij to gitignore

### PR DESCRIPTION
**Pull request by petehayes**

### CODE REVIEW

**Comment by cdancy** [comment]
@petehayes lets use this PR as a test for wiring up public CI (believe we decided on circle-ci if I'm not mistaken).

**Comment by petehayes** [comment]
Sounds good.

**Comment by cdancy** [comment]
You've got some conflicts you need to fix on account of changes I made to flesh out the greater project structure.

**Comment by petehayes** [comment]
Rebased and pushed

**Comment by cdancy** [comment]
hmmm ... I _thought_ I wired up circle-ci correctly and your push should have triggered ...something. I'll have to look into that.

**Comment by petehayes** [comment]
I just allowed access to the organization to circle-ci if that helps.  Do we need to have a CI script or something checked into the repo?

**Comment by cdancy** [comment]
Reading over docs I _thought_ it was not necessary if all you're doing is a typical `./gradlew clean build`. I'll add one anyway with some typical configs if only to show others how its done.

**Comment by petehayes** [comment]
You are right. I pushed a couple changes to master and they did not kick the ci build. Not sure why.

**Pull request closed without merging**
